# Generated by Django 4.2.3 on 2023-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='모임 이름')),
                ('place', models.TextField(verbose_name='모임 장소')),
                ('date', models.DateField(auto_now_add=True, verbose_name='모임 시간')),
                ('num_people', models.IntegerField(verbose_name='모집 인원')),
                ('closing_date', models.IntegerField(verbose_name='모집 마감 일자')),
                ('writer', models.TextField(verbose_name='주최자')),
                ('tag', models.CharField(choices=[('original', '바리스타 오리지널'), ('friend', '동네친구끼리 편하게'), ('tour', '핫플 카페 투어'), ('worker', '직장인 커피 모임'), ('beginner', '커피 입문자 환영'), ('why', '커피모임 왜하지')], default='original', max_length=8)),
                ('content', models.TextField(verbose_name='모집 내용')),
            ],
        ),
    ]
