# Generated by Django 4.2.4 on 2023-11-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/default.jpg', upload_to='', verbose_name='이미지')),
                ('title', models.CharField(max_length=20, verbose_name='모임이름')),
                ('content', models.TextField(verbose_name='모집 내용')),
                ('num_people', models.IntegerField(default=0, verbose_name='모집 인원')),
                ('district', models.CharField(max_length=11, verbose_name='장소')),
                ('meet_time', models.CharField(default='', max_length=11, verbose_name='모임 시간')),
                ('deadline_yy', models.IntegerField(default=2023, verbose_name='마감일 연')),
                ('deadline_mm', models.CharField(max_length=2, verbose_name='마감일 월')),
                ('deadline_dd', models.CharField(max_length=2, verbose_name='마감일 일')),
                ('organizer', models.CharField(max_length=13, verbose_name='주최자')),
                ('like', models.IntegerField(default=0, verbose_name='좋아요 개수')),
                ('iflike', models.BooleanField(default=False, verbose_name='좋아요 여부')),
                ('tag', models.CharField(choices=[('original', '바리스타 오리지널'), ('friend', '동네친구끼리 편하게'), ('tour', '핫플 카페 투어'), ('worker', '직장인 커피 모임'), ('beginner', '커피 입문자 환영'), ('why', '커피모임 왜하지')], default='original', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.club')),
            ],
        ),
        migrations.CreateModel(
            name='MyClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.club')),
            ],
        ),
    ]
