# Generated by Django 4.2.7 on 2023-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='이미지')),
                ('title', models.CharField(max_length=20, verbose_name='모임이름')),
                ('district', models.CharField(max_length=11, verbose_name='장소')),
                ('deadline_yy', models.IntegerField(default=2023, verbose_name='마감일 연')),
                ('deadline_mm', models.CharField(max_length=2, verbose_name='마감일 월')),
                ('deadline_dd', models.CharField(max_length=2, verbose_name='마감일 일')),
                ('organizer', models.CharField(max_length=13, verbose_name='주최자')),
                ('like', models.IntegerField(default=0, verbose_name='좋아요 개수')),
                ('iflike', models.BooleanField(default=False, verbose_name='좋아요 여부')),
            ],
        ),
    ]
