# Generated by Django 4.2.7 on 2023-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='meet_time',
            field=models.CharField(default='', max_length=11, verbose_name='모임 시간'),
        ),
    ]
