# Generated by Django 4.2.3 on 2023-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='closing_date',
            field=models.TextField(verbose_name='모집 마감 일자'),
        ),
    ]
